var _ = require("lodash");
type Dict = { [key: string]: string; };
// prettier-ignore
export const GoogleLanguages: Dict = {
    'Afrikaans': 'af',
    'Albanian': 'sq',
    'Amharic': 'am',
    'Arabic': 'ar',
    'Armenian': 'hy',
    'Azerbaijani': 'az',
    'Bas-que': 'eu',
    'Belarusian': 'be',
    'Bengali': 'bn',
    'Bosnian': 'bs',
    'Bulgarian': 'bg',
    'Catalan': 'ca',
    'Cebuano': 'ceb',
    'Chichewa': 'ny',
    'Chinese(Simplified)': 'zh-CN',
    'Chinese(Traditional)': 'zh-TW',
    'Corsican': 'co',
    'Croatian': 'hr',
    'Czech': 'cs',
    'Danish': 'da',
    'Dutch': 'nl',
    'English': 'en',
    'Esperanto': 'eo',
    'Estonian': 'et',
    'Filipino': 'fil',
    'Finnish': 'fi',
    'French': 'fr',
    'Frisian': 'fy',
    'Galician': 'gl',
    'Georgian': 'ka',
    'German': 'de',
    'Greek': 'el',
    'Gujarati': 'gu',
    'Haitian creole': 'ht',
    'Hausa': 'ha',
    'Hawaiian': 'haw',
    'Hebrew': 'he',
    'Hindi': 'hi',
    'Hmong': 'hmn',
    'Hungarian': 'hu',
    'Icelandic': 'is',
    'Igbo': 'ig',
    'Indonesian': 'id',
    'Irish': 'ga',
    'Italian': 'it',
    'Japanese': 'ja',
    'Javanese': 'jw',
    'Kannada': 'kn',
    'Kazakh': 'kk',
    'Khmer': 'km',
    'Korean': 'ko',
    'Kurdish(kurmanji)': 'ku',
    'Kyrgyz': 'ky',
    'Lao': 'lo',
    'Latin': 'la',
    'Latvian': 'lv',
    'Lithuanian': 'lt',
    'Luxembourgish': 'lb',
    'Macedonian': 'mk',
    'Malagasy': 'mg',
    'Malay': 'ms',
    'Malayalam': 'ml',
    'Maltese': 'mt',
    'Maori': 'mi',
    'Marathi': 'mr',
    'Mongolian': 'mn',
    'Myanmar(burmese)': 'my',
    'Nepali': 'ne',
    'Norwegian': 'no',
    'Pashto': 'ps',
    'Persian': 'fa',
    'Polish': 'pl',
    'Portuguese': 'pt',
    'Punjabi': 'pa',
    'Romanian': 'ro',
    'Russian': 'ru',
    'Samoan': 'sm',
    'Scots gaelic': 'gd',
    'Serbian': 'sr',
    'Sesotho': 'st',
    'Shona': 'sn',
    'Sindhi': 'sd',
    'Sinhala': 'si',
    'Slovak': 'sk',
    'Slovenian': 'sl',
    'Somali': 'so',
    'Spanish': 'es',
    'Sundanese': 'su',
    'Swahili': 'sw',
    'Swedish': 'sv',
    'Tajik': 'tg',
    'Tamil': 'ta',
    'Telugu': 'te',
    'Thai': 'th',
    'Turkish': 'tr',
    'Ukrainian': 'uk',
    'Urdu': 'ur',
    'Uzbek': 'uz',
    'Vietnamese': 'vi',
    'Welsh': 'cy',
    'Xhosa': 'xh',
    'Yiddish': 'yi',
    'Yoruba': 'yo',
    'Zulu': 'zu'
};

// prettier-ignore
export const BaiduLanguages:Dict =
    {
        English: 'en',
        Thai: 'th',
        Russian: 'ru',
        Portuguese: 'pt',
        Greek: 'el',
        Dutch: 'nl',
        Polish: 'pl',
        Bulgarian: 'bg',
        Estonian: 'et',
        Danish: 'da',
        Finnish: 'fi',
        Czech: 'cs',
        Romanian: 'ro',
        Slovenian: 'sl',
        Swedish: 'sv',
        Hungarian: 'hu',
        German: 'de',
        Italian: 'it',
        'Chinese(Simplified)': 'zh-CN',
        'Chinese(Traditional)': 'zh-TW',
        Japanese: 'ja',
        Korean: 'ko',
        Spanish: 'es',
        French: 'fr',
        Arabic: 'ar'
    };

// prettier-ignore
export const YoudaoLanguages:Dict = {
    English: 'en',
    Russian: 'ru',
    Portuguese: 'pt',
    Spanish: 'es',
    'Chinese(Simplified)': 'zh-CN',
    Japanese: 'ja',
    Korean: 'ko',
    French: 'fr'
};

export const GoogleCodes = _.invert(GoogleLanguages);
export const GoogleLangList = _.keys(GoogleLanguages);
export const BaiduCodes = _.invert(BaiduLanguages);
export const BaiduLangList = _.keys(BaiduLanguages);
export const YoudaoCodes = _.invert(YoudaoLanguages);
export const YoudaoLangList = _.keys(YoudaoLanguages);


export function isChineseLike(code: string): boolean {
    return code in ["zh-cn", "zh-tw", "ja"]
}


